yc_cloud_id              = "b1gos10ashr7cgusvgg9"
yc_folder_id             = "b1gm6im3mcuc36r6kn8s"
yc_zone                  = "ru-central1-a"
public_key_path          = "~/.ssh/id_rsa.pub"
private_key_path         = "~/.ssh/id_rsa"
service_account_key_file = "../YC/tf_sa_key.json"
#access_key               = "" //передаются через export
#secret_key               = ""
sa_id = "neto-robot"
